plugins {
    id 'com.android.application'
}

android {
    namespace 'br.com.thiaguinhosolucoes.otthos'
    compileSdk 35

    defaultConfig {
        applicationId 'br.com.thiaguinhosolucoes.otthos'
        minSdk 24
        targetSdk 35
        versionCode 70573
        versionName "7.0.5.7.3"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
